### ISSUE TITLE
Make openfisca-run-test --country_package option more flexible

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#530]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:

I am trying to run tests on openfisca-france-indirect-taxation (to migrate the package to the new core versions)

I tried
````
benjello@WKS-IPP-6:~/openfisca/openfisca-france-indirect-taxation(api_migration *%)$ openfisca-run-test -c "OpenFisca-France-Indirect-Taxation" openfisca_france_indirect_taxation/tests/formulas/
ERROR: Traceback (most recent call last):
  File "/home/benjello/openfisca/openfisca-core/openfisca_core/scripts/__init__.py", line 31, in build_tax_benefit_sytem
    country_package = importlib.import_module(country_package_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named OpenFisca-France-Indirect-Taxation

Could not import module `OpenFisca-France-Indirect-Taxation`.
Are you sure it is installed in your environment? If so, look at the stack trace above to determine the origin of this error.
See more at <https://github.com/openfisca/country-template#installing>.
````
and 
````
benjello@WKS-IPP-6:~/openfisca/openfisca-france-indirect-taxation(api_migration *%)$ openfisca-run-test -c openfisca-france-indirect-taxation openfisca_france_indirect_taxation/tests/formulas/
ERROR: Traceback (most recent call last):
  File "/home/benjello/openfisca/openfisca-core/openfisca_core/scripts/__init__.py", line 31, in build_tax_benefit_sytem
    country_package = importlib.import_module(country_package_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named openfisca-france-indirect-taxation

Could not import module `openfisca-france-indirect-taxation`.
Are you sure it is installed in your environment? If so, look at the stack trace above to determine the origin of this error.
See more at <https://github.com/openfisca/country-template#installing>.
````
but only the following worked

````
benjello@WKS-IPP-6:~/openfisca/openfisca-france-indirect-taxation(api_migration *%)$ openfisca-run-test -c openfisca_france_indirect_taxation openfisca_france_indirect_taxation/tests/formulas/
````

### Here is what I expected to happen:

Every call should have worked (minimal surprise principle)

### Here is what actually happened:

Only the last worked

## Context

I identify more as a:

- Analyst _(I make macroscopic computations on real populations)_.

**Comment by Morendil** [comment]
Closing this as stale.
