### ISSUE TITLE
Explicit format error in YAML test file

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-core#755]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:
`openfisca-run-test tmp.yaml`
with
```yaml
output_variables:
  rsa: 551
relative_margin_error: 0.01
period: 2018-10
```
### Here is what I expected to happen:

An actionable error message expliciting the key error:
`relative_margin_error` should be `relative_error_margin`

### Here is what actually happened:
```
E
======================================================================
ERROR: test suite
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/thomas/repos/mes-aides-ui/.venv/local/lib/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/home/thomas/repos/mes-aides-ui/.venv/local/lib/python2.7/site-packages/nose/suite.py", line 270, in setUp
    if not self:
  File "/home/thomas/repos/mes-aides-ui/.venv/local/lib/python2.7/site-packages/nose/suite.py", line 85, in __nonzero__
    test = self.test_generator.next()
  File "/home/thomas/repos/mes-aides-ui/.venv/local/lib/python2.7/site-packages/openfisca_core/tools/test_runner.py", line 84, in generate_tests
    for test in _generate_tests_from_file(tax_benefit_system, path, options):
  File "/home/thomas/repos/mes-aides-ui/.venv/local/lib/python2.7/site-packages/openfisca_core/tools/test_runner.py", line 136, in _generate_tests_from_file
    for test_index, (path_to_file, name, period_str, test) in enumerate(tests, 1):
  File "/home/thomas/repos/mes-aides-ui/.venv/local/lib/python2.7/site-packages/openfisca_core/tools/test_runner.py", line 218, in _parse_test_file
    default_flow_style = False, indent = 2, width = 120)))
  File "/home/thomas/repos/mes-aides-ui/.venv/local/lib/python2.7/site-packages/yaml/__init__.py", line 202, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/home/thomas/repos/mes-aides-ui/.venv/local/lib/python2.7/site-packages/yaml/__init__.py", line 190, in dump_all
    dumper.represent(data)
  File "/home/thomas/repos/mes-aides-ui/.venv/local/lib/python2.7/site-packages/yaml/representer.py", line 29, in represent
    self.serialize(node)
  File "ext/_yaml.pyx", line 1348, in _yaml.CEmitter.serialize
  File "ext/_yaml.pyx", line 1510, in _yaml.CEmitter._serialize_node
  File "ext/_yaml.pyx", line 1431, in _yaml.CEmitter._serialize_node
TypeError: value must be a string

----------------------------------------------------------------------
Ran 0 tests in 0.002s

FAILED (errors=1)

```

## Context

I identify more as a:
- Developer _(I create tools that use the existing OpenFisca code)_.

**Comment by Morendil** [comment]
Schema-based validation could be a good idea here, for beta.gouv.fr [Kwalify](http://www.kuwata-lab.com/kwalify/) did the job nicely. One possible issue is that all the input variable and period keys do not actually come from a fixed set. Kwalify can handle that with custom validation hooks.

**Comment by fpagnoux** [comment]
I think schema validation was not chosen as it was, at least 2 years ago, _really slow_ in YAML

**Comment by Morendil** [comment]
It could still be useful as an on-demand diagnosis tool for humans' convenience (and we could consider a failing YAML test to be a "demand" and run it automatically in these cases).

**Comment by fpagnoux** [comment]
Since #781, the error message in that case would be:

```
ValueError: Unexpected keys {'absolute_margin_error'} in test 'Income tax for a single parent and a child' in file '/Users/florianpagnoux/Dev/openfisca/country-template/openfisca_country_template/tests/situations/income_tax.yaml'
```

That seem much more readable that the problematic one reported by @guillett .
