### ISSUE TITLE
Limit test writers, readers, migrators frustration :crying:

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-core#799]
Hi there!

I am quite frustrated when using OpenFisca. I recently encountered an issue.

### Here is what I did:

I am currently migrating from v24 to v25 (test syntax) [4 extensions](https://github.com/betagouv/mes-aides-ui/blob/master/openfisca/requirements.txt#L4-L7) used in our simulator.

- I used the migration script but it changed the test files too much and, to me, create really hard to read tests ; especially when there are multiple tests in a single file.
- I migrated a test manually as the migration script was too invasive for me and I had the follow unhelpful help message:

```
(venv-ofp) ➜  openfisca_paris git:(update_of) ✗ openfisca-run-test ../tests/unittests/aspeh.yaml --extensions openfisca_paris
No handlers could be found for logger "openfisca_core.parameters"
/home/thomas/repos/openfisca-core/openfisca_core/scripts/run_test.py:31: Warning: The 'openfisca-run-test' command has been deprecated in favor of 'openfisca test' since version 25.0, and will be removed in the future.
  Warning
.Traceback (most recent call last):
  File "/home/thomas/repos/venv-ofp/bin/openfisca-run-test", line 11, in <module>
    load_entry_point('OpenFisca-Core', 'console_scripts', 'openfisca-run-test')()
  File "/home/thomas/repos/openfisca-core/openfisca_core/scripts/run_test.py", line 47, in main
    tests_ok = run_tests(tax_benefit_system, paths, options)
  File "/home/thomas/repos/openfisca-core/openfisca_core/tools/test_runner.py", line 111, in run_tests
    argv = argv,
  File "/home/thomas/repos/venv-ofp/local/lib/python2.7/site-packages/nose/core.py", line 301, in run
    return TestProgram(*arg, **kw).success
  File "/home/thomas/repos/venv-ofp/local/lib/python2.7/site-packages/nose/core.py", line 121, in __init__
    **extra_args)
  File "/usr/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/home/thomas/repos/venv-ofp/local/lib/python2.7/site-packages/nose/core.py", line 207, in runTests
    result = self.testRunner.run(self.test)
  File "/home/thomas/repos/venv-ofp/local/lib/python2.7/site-packages/nose/core.py", line 62, in run
    test(result)
  File "/home/thomas/repos/venv-ofp/local/lib/python2.7/site-packages/nose/suite.py", line 177, in __call__
    return self.run(*arg, **kw)
  File "/home/thomas/repos/venv-ofp/local/lib/python2.7/site-packages/nose/suite.py", line 217, in run
    for test in self._tests:
  File "/home/thomas/repos/venv-ofp/local/lib/python2.7/site-packages/nose/suite.py", line 372, in _get_wrapped_tests
    for test in self._get_tests():
  File "/home/thomas/repos/venv-ofp/local/lib/python2.7/site-packages/nose/suite.py", line 99, in _get_tests
    for test in self.test_generator:
  File "/home/thomas/repos/openfisca-core/openfisca_core/tools/test_runner.py", line 75, in generate_tests
    for test in _generate_tests_from_file(tax_benefit_system, path, options):
  File "/home/thomas/repos/openfisca-core/openfisca_core/tools/test_runner.py", line 126, in _generate_tests_from_file
    for test_index, (simulation, test) in enumerate(tests, 1):
  File "/home/thomas/repos/openfisca-core/openfisca_core/tools/test_runner.py", line 184, in _parse_test_file
    yield _parse_test(tax_benefit_system, test, options, yaml_path)
  File "/home/thomas/repos/openfisca-core/openfisca_core/tools/test_runner.py", line 216, in _parse_test
    raise ValueError("Unexpected keys {} in test '{}' in file '{}'".format(unexpected_keys, name, yaml_path))
ValueError: <exception str() failed>
```
For some reason [that line](https://github.com/openfisca/openfisca-core/blob/master/openfisca_core/tools/test_runner.py#L216) is broken in my setup (Python 2.7).

- I thought it would be easy to reproduce this bug in Python 3 and on the contry-template. I cloned the repo and created a virtualenv. I tried to run a test without any change.

```
(venv-ct3) ➜  country-template git:(master) openfisca-run-test openfisca_country_template/tests/age.yaml                 
libyaml is not installed in your environment. This can make OpenFisca slower to start. Once you have installed libyaml, run 'pip uninstall pyyaml && pip install pyyaml --no-cache-dir' so that it is used in your Python environment.

Traceback (most recent call last):
  File "/home/thomas/repos/venv-ct3/lib/python3.6/site-packages/openfisca_core/tools/test_runner.py", line 34, in import_yaml
    from yaml import CLoader as Loader
ImportError: cannot import name 'CLoader'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thomas/repos/venv-ct3/bin/openfisca-run-test", line 7, in <module>
    from openfisca_core.scripts.run_test import main
  File "/home/thomas/repos/venv-ct3/lib/python3.6/site-packages/openfisca_core/scripts/run_test.py", line 10, in <module>
    from openfisca_core.tools.test_runner import run_tests
  File "/home/thomas/repos/venv-ct3/lib/python3.6/site-packages/openfisca_core/tools/test_runner.py", line 48, in <module>
    yaml, Loader = import_yaml()
  File "/home/thomas/repos/venv-ct3/lib/python3.6/site-packages/openfisca_core/tools/test_runner.py", line 36, in import_yaml
    log.warning(
NameError: name 'log' is not defined
```

- Then I `pip install --editable ../openfisca-core`
- Got the same error message
- I moved [that line](https://github.com/openfisca/openfisca-core/blob/master/openfisca_core/tools/test_runner.py#L50) on the 24th line.
- And got

```
(venv-ct3) ➜  country-template git:(master) openfisca-run-test openfisca_country_template/tests/age.yaml
libyaml is not installed in your environment. This can make OpenFisca slower to start. Once you have installed libyaml, run 'pip uninstall pyyaml && pip install pyyaml --no-cache-dir' so that it is used in your Python environment.

 libyaml is not installed in your environment, this can make your test suite slower to run. Once you have installed libyaml, run `pip uninstall pyyaml && pip install pyyaml --no-cache-dir` so that it is used in your Python environment.
/home/thomas/repos/openfisca-core/openfisca_core/scripts/run_test.py:31: Warning: The 'openfisca-run-test' command has been deprecated in favor of 'openfisca test' since version 25.0, and will be removed in the future.
  Warning
Traceback (most recent call last):
  File "/home/thomas/repos/openfisca-core/openfisca_core/scripts/__init__.py", line 60, in detect_country_package
    module = importlib.import_module(module_name)
  File "/home/thomas/repos/venv-ct3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 888, in get_code
  File "<frozen importlib._bootstrap_external>", line 455, in _validate_bytecode_header
ImportError: bad magic number in 'openfisca_web_api_preview': b'\x03\xf3\r\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thomas/repos/venv-ct3/bin/openfisca-run-test", line 11, in <module>
    load_entry_point('OpenFisca-Core', 'console_scripts', 'openfisca-run-test')()
  File "/home/thomas/repos/openfisca-core/openfisca_core/scripts/run_test.py", line 37, in main
    tax_benefit_system = build_tax_benefit_system(args.country_package, args.extensions, args.reforms)
  File "/home/thomas/repos/openfisca-core/openfisca_core/scripts/__init__.py", line 23, in build_tax_benefit_system
    country_package_name = detect_country_package()
  File "/home/thomas/repos/openfisca-core/openfisca_core/scripts/__init__.py", line 65, in detect_country_package
    raise ImportError(message)
ImportError: Traceback (most recent call last):
  File "/home/thomas/repos/openfisca-core/openfisca_core/scripts/__init__.py", line 60, in detect_country_package
    module = importlib.import_module(module_name)
  File "/home/thomas/repos/venv-ct3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 888, in get_code
  File "<frozen importlib._bootstrap_external>", line 455, in _validate_bytecode_header
ImportError: bad magic number in 'openfisca_web_api_preview': b'\x03\xf3\r\n'

Could not import module `openfisca_web_api_preview`.
Look at the stack trace above to determine the error that stopped installed modules detection.
```

I am stopping here because I can't invest more time in that.
I am still a few versions behind but it is too costly to upgrade.

Reading other issues (https://github.com/openfisca/openfisca-core/issues/755, https://github.com/openfisca/openfisca-core/issues/782)  I logged on Core, I am wondering whether:
- I am too vocal and the problem is with me or
- there are (serious?) problems with providing helpful messages to contributors.

**Comment by Morendil** [comment]
As discussed IRL, "bad magic number" is often seen when switching from one Python version to another and reusing a compiled `.pyc` file. The solution usually involves `make clean` to get rid of the compiled files.

**Comment by guillett** [comment]
Many thanks @Morendil your help and support is precious.

**Comment by guillett** [comment]
```
(venv-ofp) ➜  openfisca-paris git:(aspeh-test) ✗ pip list
Package            Version Location                          
------------------ ------- ----------------------------------
Babel              2.6.0   
Biryani            0.10.8  
dpath              1.4.0   
enum34             1.1.6   
future             0.17.1  
isodate            0.6.0   
nose               1.3.7   
numexpr            2.6.8   
numpy              1.15.4  
OpenFisca-Core     25.2.2  
OpenFisca-France   32.3.0  
Openfisca-Paris    2.2.0   /home/thomas/repos/openfisca-paris
pip                18.1    
psutil             5.4.6   
pytz               2018.7  
PyYAML             3.13    
ruamel.ordereddict 0.4.13  
ruamel.yaml        0.15.81 
setuptools         40.6.3  
six                1.12.0  
sortedcontainers   1.5.9   
wheel              0.32.3  
```
