### ISSUE TITLE
How to create several simulations with reformed taxes but the same entities and variables

### ISSUE THREAD

**Issue by magemax** [openfisca/openfisca-core#848]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:

I used the method build() in SimulationBuilder  twice, with 2 different tax benefit systems (one with a reform applied and one without)

```python
tbs = FranceTaxBenefitSystem()
sb = SimulationBuilder()
#... lots of lines defining all entities in sb and links between them and filling variables ...
simulation1 = sb.build(tbs)
new_tax_benefit_system = apply_reform(tbs)
simulation2 = sb.build(new_tax_benefit_system)
```

### Here is what I expected to happen:

I expected simulation and simulation2 to return different results, simulation2 taking into account the reform,  simulation1 not taking it into account

### Here is what actually happened:

Both simulations return the same result,  forcing me to create two SimulationBuilder()  and to repeat the numerous steps of inputting the entities and variables in them.

## Context

I identify more as a:
- Developer

**Comment by magemax** [comment]
went through the problem more in depth with @Morendil .  The issue actually happens when the following operations are executed : 

A simulation builder is created
Entities are inputted in it
Two simulations are build from the simulation builder
Inputs are set in the two simulations

At the last step, some inputs fail to be set in the second simulation while they all worked for the first one : 

```
input setting failed for input chomage_brut and simulation 2 in table individu
Traceback (most recent call last):
  File "<input>", line 104, in <module>
  File "c:\eig\openfiscagits\openfisca-core\openfisca_core\simulations.py", line 481, in set_input
    self.get_holder(variable).set_input(period, value)
  File "c:\eig\openfiscagits\openfisca-core\openfisca_core\holders.py", line 186, in set_input
    return self.variable.set_input(self, period, array)
  File "c:\eig\openfiscagits\openfisca-core\openfisca_core\holders.py", line 329, in set_input_divide_by_period
    remaining_array -= existing_array
TypeError: Cannot cast ufunc subtract output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
```

**Comment by Morendil** [comment]
#857 should improve the situation a bit, and make the fix easier to express: two simulations can share the same *entities* but not the same *populations*.

**Comment by Morendil** [comment]
Potentially a "good first bug" for Core contributors, as there is a usable workaround (instantiate two distinct `SimulationBuilder`s) so the urgency is low, and the fix is relatively clear - clone populations when `build()` is called instead of reusing the same populations.
